all: tarball

tarball: aliases email-addresses exim rpm selinux ssh sysctl.conf yum.conf yum.repos.d
	tar -cf centos.tar aliases email-addresses  exim rpm  selinux ssh sysctl.conf yum.conf yum.repos.d
